"""Baseline version stamping -- self-describing baselines (DDIA Ch4 pattern).

Stamps .secrets.baseline files with the detector version and active plugin list,
so users know which version created the baseline and whether an upgrade will
cause drift.

A baseline's top-level JSON already carries 'version', 'plugins_used',
'filters_used', and 'results'.  This module adds a 'generated_by' key that
records the exact detector build and plugin manifest at creation time, letting
you diff two snapshots to see what changed.
"""

import json
import time
from typing import Any
from typing import Dict
from typing import List

from ..__version__ import VERSION


def _get_all_plugin_classes() -> List[Dict[str, str]]:
    """Return sorted list of {name, secret_type} for every discoverable plugin."""
    from ..core.plugins.util import get_mapping_from_secret_type_to_class

    mapping = get_mapping_from_secret_type_to_class()
    return sorted(
        [
            {
                'name': cls.__name__,
                'secret_type': secret_type,
            }
            for secret_type, cls in mapping.items()
        ],
        key=lambda x: x['name'].lower(),
    )


def get_current_stamp() -> Dict[str, Any]:
    """Return a dict describing the current detector configuration.

    The stamp captures:
      - version: detect-secrets version string
      - plugins: every registered plugin with its class name and secret_type
      - plugin_count: convenience integer for quick comparison
      - stamp_time: ISO-8601 UTC timestamp
    """
    plugins = _get_all_plugin_classes()
    return {
        'version': VERSION,
        'plugins': plugins,
        'plugin_count': len(plugins),
        'stamp_time': time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()),
    }


def stamp_baseline(baseline_path: str) -> Dict[str, Any]:
    """Add or update the 'generated_by' key in a baseline file.

    Reads the baseline JSON, injects the current stamp under 'generated_by',
    and writes it back.  The existing 'version', 'plugins_used', 'filters_used',
    and 'results' keys are untouched.

    Returns the stamp that was written.
    """
    with open(baseline_path) as f:
        baseline = json.load(f)

    stamp = get_current_stamp()
    baseline['generated_by'] = stamp

    with open(baseline_path, 'w') as f:
        f.write(json.dumps(baseline, indent=2) + '\n')

    return stamp


def check_baseline_compat(baseline_path: str) -> Dict[str, Any]:
    """Check whether a baseline was generated by a compatible configuration.

    Compares the 'generated_by' stamp inside the baseline file against
    the current detector's stamp.

    Returns a dict with:
      - compatible: True if version matches AND plugin sets are identical
      - version_match: True if the version strings are equal
      - current_stamp: the live detector stamp (without stamp_time)
      - baseline_stamp: the stamp read from the file (None if unstamped)
      - added_plugins: plugin names present now but absent when baseline was created
      - removed_plugins: plugin names in the baseline but no longer available
    """
    with open(baseline_path) as f:
        baseline = json.load(f)

    current = get_current_stamp()
    baseline_stamp = baseline.get('generated_by')

    if baseline_stamp is None:
        return {
            'compatible': False,
            'version_match': False,
            'current_stamp': current,
            'baseline_stamp': None,
            'added_plugins': [p['name'] for p in current['plugins']],
            'removed_plugins': [],
            'note': 'Baseline has no generated_by stamp. Run stamp_baseline() to add one.',
        }

    current_names = {p['name'] for p in current['plugins']}
    baseline_names = {p['name'] for p in baseline_stamp.get('plugins', [])}

    added = sorted(current_names - baseline_names)
    removed = sorted(baseline_names - current_names)
    version_match = current['version'] == baseline_stamp.get('version')

    return {
        'compatible': version_match and not added and not removed,
        'version_match': version_match,
        'current_stamp': current,
        'baseline_stamp': baseline_stamp,
        'added_plugins': added,
        'removed_plugins': removed,
    }
